oyvindwe/connectlife-ha

custom_components/connectlife/__init__.py
custom_components/connectlife/coordinator.py
custom_components/connectlife/entity.py
custom_components/connectlife/manifest.json
custom_components/connectlife/sensor.py

- Set up coordinator in __init__ (preparing for multiple platforms)
- Write state to HA after updating - fixes issue #2 
- Support unloading integration
- Bump version to 0.0.6

Coordinator fixes

---

custom_components/connectlife/data_dictionaries/015-000.yaml
custom_components/connectlife/data_dictionaries/README.md
custom_components/connectlife/dictionaries.py
custom_components/connectlife/sensor.py

Defaults any integer property to sensor state class `measurement`, so this should fix issue #5

Framework for data dictionaries

---

custom_components/connectlife/data_dictionaries/015-000.yaml
custom_components/connectlife/data_dictionaries/README.md
custom_components/connectlife/dictionaries.py
custom_components/connectlife/sensor.py
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json

- Set icon in data dictionary
- Support property name as translation key

Sensor improvements

---

custom_components/connectlife/__init__.py
custom_components/connectlife/binary_sensor.py
custom_components/connectlife/data_dictionaries/015-000.yaml
custom_components/connectlife/data_dictionaries/README.md
custom_components/connectlife/data_dictionaries/properties-schema.json
custom_components/connectlife/dictionaries.py
custom_components/connectlife/sensor.py
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json

Also added JSON schema for data dictionaries.

Support binary_sensor

---

custom_components/connectlife/binary_sensor.py
custom_components/connectlife/climate.py
custom_components/connectlife/entity.py
custom_components/connectlife/select.py
custom_components/connectlife/sensor.py
custom_components/connectlife/switch.py

Fix climate entity name

---

custom_components/connectlife/climate.py
custom_components/connectlife/const.py
custom_components/connectlife/data_dictionaries/009-109.yaml
custom_components/connectlife/data_dictionaries/README.md
custom_components/connectlife/data_dictionaries/properties-schema.json
custom_components/connectlife/dictionaries.py

- 009-109: Map t_work_mode to hvac_mode instead

Support HVAC mode for climate

---

custom_components/connectlife/humidifier.py

Set humidifier mode

---

custom_components/connectlife/climate.py
custom_components/connectlife/data_dictionaries/009-109.yaml
custom_components/connectlife/data_dictionaries/README.md
custom_components/connectlife/data_dictionaries/properties-schema.json
custom_components/connectlife/dictionaries.py
custom_components/connectlife/humidifier.py
custom_components/connectlife/sensor.py
custom_components/connectlife/services.yaml

- Climate: for target_humidity and target_temperature
- Humidifier: for target_humidity
- Sensor: added configurable minimum value for set_value service

Configurable minimum and maximum values

---

custom_components/connectlife/manifest.json

Release notes: [0.3.0](https://github.com/oyvindwe/connectlife/releases/tag/v0.3.0)
Full Changelog: [`v0.2.0...v0.3.0`](https://github.com/oyvindwe/connectlife/compare/v0.2.0...v0.3.0)

Update connectlife to 0.3.0

---

custom_components/connectlife/manifest.json

- Release notes: [0.4.0](https://github.com/oyvindwe/connectlife/releases/tag/v0.4.0)
- Full Changelog: [`v0.3.0...v0.4.0`](https://github.com/oyvindwe/connectlife/compare/v0.3.0...v0.4.0)

Update connectlife to 0.4.0

---

custom_components/connectlife/data_dictionaries/016-502.yaml
custom_components/connectlife/data_dictionaries/README.md
custom_components/connectlife/data_dictionaries/properties-schema.json
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json
custom_components/connectlife/water_heater.py

Water heater: Fix turning off

---

custom_components/connectlife/manifest.json

- Release notes: [0.5.0](https://github.com/oyvindwe/connectlife/releases/tag/v0.5.0)
- Full Changelog: [`v0.4.0...v0.5.0`](https://github.com/oyvindwe/connectlife/compare/v0.4.0...v0.5.0)

Update connectlife to 0.5.0

---

custom_components/connectlife/binary_sensor.py
custom_components/connectlife/climate.py
custom_components/connectlife/coordinator.py
custom_components/connectlife/entity.py
custom_components/connectlife/humidifier.py
custom_components/connectlife/number.py
custom_components/connectlife/select.py
custom_components/connectlife/sensor.py
custom_components/connectlife/switch.py
custom_components/connectlife/water_heater.py

- Use coordinator.data
- Update coordinator.data and notify listeners after api.update_appliance

Refactor update device

---

custom_components/connectlife/water_heater.py

Fix setting min and max temperature for water heater

---

custom_components/connectlife/data_dictionaries/007-400.yaml
custom_components/connectlife/data_dictionaries/009-109.yaml
custom_components/connectlife/icons.json

Added more icons

---

README.md
custom_components/connectlife/data_dictionaries/009-104.yaml
custom_components/connectlife/data_dictionaries/009-109.yaml
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json

- Added sleep modes to 009-109 (aircondition)

Text and icon adjustments

---

custom_components/connectlife/number.py

- Fix regression when creating entity (introduced in PR #57)
- Fix regression when setting value (introduced in PR #57)

Fix number entity

---

custom_components/connectlife/climate.py

Fix reload integration with climate entity

---

custom_components/connectlife/climate.py
custom_components/connectlife/config_flow.py
custom_components/connectlife/const.py
custom_components/connectlife/data_dictionaries/016-502.yaml
custom_components/connectlife/entity.py
custom_components/connectlife/humidifier.py
custom_components/connectlife/number.py
custom_components/connectlife/select.py
custom_components/connectlife/strings.json
custom_components/connectlife/switch.py
custom_components/connectlife/translations/en.json
custom_components/connectlife/water_heater.py

As reported in https://github.com/oyvindwe/connectlife/issues/13

Option flow to disable beep

---

custom_components/connectlife/data_dictionaries/007-406.yaml
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json

This adds another Dehumidifier model under 007-406. It is similar to the already existing dehumidifier dictionary but additionally contains a clothes drying feature.
Tested on Hisense D20HW Dehumidifier

Added 007-406 (Dehumidifier with clothes dry feature)

---

README.md
custom_components/connectlife/data_dictionaries/020-63c45b513e1a4bf7.yaml
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json

Added 020-63c45b513e1a4bf7 (Atag induction hob)

---

custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json

Sleep as a switch is a function of 006-200 (#97)

Add t_sleep switch to translations

---

custom_components/connectlife/data_dictionaries/009-100.yaml

Same as other 009-10x under testing but currently working

Integration of 009-100 Hardware

---

custom_components/connectlife/coordinator.py

- Will try 3 times to get data before reporting error or timeout to Home Assistant
Fixes issue #86 and #101

Retry ConnectLife API error/timeout

---

README.md
custom_components/connectlife/data_dictionaries/006-201.yaml
custom_components/connectlife/manifest.json

- Removed unused icon
- Update documentation

Version 0.16.0

---

custom_components/connectlife/data_dictionaries/009-129.yaml
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json
custom_components/connectlife/translations/it.json

I added the device 009-129 which was not present and has new functions (e.g. purifier and smart eye) I also translated it into Italian if it can help... I personally tried all the functions without encountering any problems. Thanks for the wonderful work you did

Added device 009-129 (air conditioner)

---

custom_components/connectlife/data_dictionaries/006-200.yaml

This device seems to be the same as device 006-201. Everything seems to be working fine with my Portable air conditioner.

Added device 006-200 (air conditioner)

---

README.md
custom_components/connectlife/manifest.json

- Updated list of known devices

Version 0.17.0

---

custom_components/connectlife/climate.py

Climate: set target temperature when turning device on or changing mode

---

custom_components/connectlife/binary_sensor.py
custom_components/connectlife/data_dictionaries/009-104.yaml
custom_components/connectlife/data_dictionaries/009-106.yaml
custom_components/connectlife/data_dictionaries/009-109.yaml
custom_components/connectlife/data_dictionaries/README.md
custom_components/connectlife/data_dictionaries/properties-schema.json
custom_components/connectlife/dictionaries.py
custom_components/connectlife/number.py
custom_components/connectlife/select.py
custom_components/connectlife/sensor.py
custom_components/connectlife/switch.py

Support disabling properties

---

README.md
custom_components/connectlife/data_dictionaries/009-117.yaml

Tested configuration in my home, everything seems working.

Added Device 009-117

---

custom_components/connectlife/data_dictionaries/026-1b0610z0049j.yaml
custom_components/connectlife/data_dictionaries/README.md
custom_components/connectlife/data_dictionaries/properties-schema.json
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json
scripts/gen_strings.py

- Tool to generate missing strings
- Added missing strings
- Disable reserved properties
- Corrected typo in properties schema

Properties cleanup

---

custom_components/connectlife/manifest.json

Release notes: https://github.com/oyvindwe/connectlife/releases/tag/v0.5.2

connectlife 0.5.1 -> 0.5.2

---

.github/workflows/hassfest.yaml
README.md
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json
scripts/gen_strings.py

- Sort strings
- Replace space with underscore in translation keys in gen_strings as well
- Updated README

Minor fixes

---

custom_components/connectlife/binary_sensor.py
custom_components/connectlife/climate.py
custom_components/connectlife/coordinator.py
custom_components/connectlife/entity.py
custom_components/connectlife/humidifier.py
custom_components/connectlife/number.py
custom_components/connectlife/select.py
custom_components/connectlife/sensor.py
custom_components/connectlife/switch.py
custom_components/connectlife/water_heater.py

- Fix entity cleanup for entities that have changed platform
- Create issues for unavailable devices without entities

Fix registry cleanup

---

custom_components/connectlife/__init__.py
custom_components/connectlife/coordinator.py
custom_components/connectlife/manifest.json

- Bump connectlife to 0.5.3
- Increase timeout for fetching data
- Version 0.20.2

Handle login error

---

custom_components/connectlife/data_dictionaries/012-000.yaml

Added 012-000 hood mapping with controls for:
* LightBrightness
* LightColorTemperature 
* MotorLevel

 Added controls for LightBrightness, LightColorTemperature and MotorLevel to the 012-000 hood

---

custom_components/connectlife/data_dictionaries/025-1wj120389v0b.yaml
custom_components/connectlife/data_dictionaries/030-1wk100130v0f.yaml

- Hisense 5s Tumble Dryer https://hisense.co.za/products/hisense-dh5s102bb-5s-series-10kg-premium-black-heat-pump-tumbler-dryer/
- Hisense 5s washing machine https://hisense.co.za/products/hisense-wf5s1045bb-5s-series-10-5kg-premium-black-front-loader/

Hisense 5S Washing Machine (WFSE1214-MVW002) & Tumble Dryer (DHSE10)

---

custom_components/connectlife/water_heater.py

Due to this change https://github.com/home-assistant/core/pull/132888 in Home Assistant 2025.1

Ensure compatibility with Home Assistant 2025.1

---

README.md
custom_components/connectlife/data_dictionaries/015-dishwasher-50.2f.yaml
custom_components/connectlife/translations/en.json

Added support for Gorenje GS673B60W (015-dishwasher-50.2f)

---

custom_components/connectlife/data_dictionaries/015-dishwasher-50.2t.yaml

The mapping file retrieved through the API had exactly the same properties as 015-dishwasher-50.2f.yaml so I copied that file.

Added mapping file for Pelgrim GVWC330L

---

custom_components/connectlife/manifest.json

Release notes: https://github.com/oyvindwe/connectlife/releases/tag/v0.5.4
Full Changelog: https://github.com/oyvindwe/connectlife/compare/v0.5.3...v0.5.4

Bump connectlife to 0.5.4

---

README.md

Document workaround for SSO users

---

custom_components/connectlife/data_dictionaries/026-1b0628z0075j.yaml

Added device 026-1b0628z0075j (HiSense RS819N4ISU fridge)

---

README.md
custom_components/connectlife/data_dictionaries/026-1b0628z0146j.yaml

I added 026-1b0628z0146j (Hisense Refrigerator RS818N4TIE1).
The binary sensors show Off in HA, even though they should get the value 1.
```
- property: existing_holiday_mode
binary_sensor: {}
```

Add 026-1b0628z0146j (Hisense Refrigerator RS818N4TIE1)

---

custom_components/connectlife/translations/es.json

Spanish Translation file added.

Spanish Translation

---

custom_components/connectlife/data_dictionaries/025-1wj090660v0w.yaml
custom_components/connectlife/translations/es.json

New device 025 025-1wj090660v0w.yaml washer-dryer

Add device 025-1wj090660v0w (washing machine)

---

custom_components/connectlife/__init__.py
custom_components/connectlife/config_flow.py

Fix options flow handler

---

README.md
custom_components/connectlife/data_dictionaries/027-washing-machine-wm22.yaml
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json

Adding mapping files for WPNA84A2TSWIFI/PL

Add 027-washing-machine-wm22 (washing machine WPNA84A2TSWIFI/PL)

---

custom_components/connectlife/climate.py
custom_components/connectlife/water_heater.py

Set temperature limits when configuring target temperature

---

custom_components/connectlife/data_dictionaries/properties-schema.json
custom_components/connectlife/dictionaries.py
custom_components/connectlife/strings.json
custom_components/connectlife/translations/en.json
scripts/gen_strings.py

- Made properties section optional
- Updated strings

Properties fixes
