- custom_components/connectlife/entity.py
- custom_components/connectlife/manifest.json
- custom_components/connectlife/sensor.py
- custom_components/connectlife/services.yaml
- custom_components/connectlife/strings.json
- custom_components/connectlife/translations/en.json
Service to set value on a ConnectLife status entity.
Note that there is no validation if the value is supported, or if the property is writeable.
Fixes #1
> Set value service

- custom_components/connectlife/climate.py
- custom_components/connectlife/data_dictionaries/009-109.yaml
- custom_components/connectlife/data_dictionaries/README.md
- custom_components/connectlife/data_dictionaries/properties-schema.json
- custom_components/connectlife/dictionaries.py
- custom_components/connectlife/humidifier.py
- custom_components/connectlife/manifest.json
- custom_components/connectlife/select.py
- custom_components/connectlife/sensor.py
- Support more than one climate device
- Support more than one humidifier device
- Improve logging
- Add unknown_value to climate targets
- Support target action for humidifier
- 009-109: f_humidity unknown_value
- Version 0.6.0
> Version 0.6.0

- custom_components/connectlife/services.yaml
Fixes the issue that connectlife entities did not show up when using service `set_value` in the developer tools UI.
> Fix target entities for service set_value

- custom_components/connectlife/humidifier.py
Humidifier was broken in version 0.7.0 due to a copy&paste error in PR #34.
> Fix humidifier regression

- custom_components/connectlife/data_dictionaries/016-502.yaml
- `t_temp_type` does not exist for this device
> 016-502 (water heater): Removed target `temperature_unit`

- custom_components/connectlife/dictionaries.py
- Sensor device classes date and timestamp do not have unit.
- Use correct device classes for number entities.
> Dictionaries fixes

- custom_components/connectlife/data_dictionaries/009-128.yaml
- custom_components/connectlife/strings.json
- custom_components/connectlife/translations/en.json
Added my model of AC. Seems similar to existing model 09-100, so copied but adjusted presets for my own use case. 
Further improvements to data_dictionary for this model and possibly others: 
- property f_votage corresponds to grid voltage, as measured by the indoor unit. 
Couldn't get this to work to add it as a property with the correct sensor device class. 
- property f_cool_qvalue corresponds to the BTU/hr of the unit, how much heat it's removing at that moment. Cool data to know how "hard" the aircon is working at a certain point in time.
- property t_fan_speed_s remains equal to t_fan_speed, so this property can probably be disabled by default?
> Added device 009-128 (air conditioner)

- custom_components/connectlife/data_dictionaries/006-200.yaml
- custom_components/connectlife/data_dictionaries/006-201.yaml
- custom_components/connectlife/data_dictionaries/007-400.yaml
- custom_components/connectlife/data_dictionaries/007-406.yaml
- custom_components/connectlife/data_dictionaries/009-104.yaml
- custom_components/connectlife/data_dictionaries/009-106.yaml
- custom_components/connectlife/data_dictionaries/009-109.yaml
- custom_components/connectlife/data_dictionaries/009-117.yaml
- custom_components/connectlife/data_dictionaries/009-128.yaml
- custom_components/connectlife/data_dictionaries/009-129.yaml
- custom_components/connectlife/data_dictionaries/015-000.yaml
- custom_components/connectlife/data_dictionaries/016-502.yaml
- custom_components/connectlife/data_dictionaries/020-63c45b513e1a4bf7.yaml
- custom_components/connectlife/data_dictionaries/026-1b0610z0049j.yaml
- custom_components/connectlife/data_dictionaries/032-000.yaml
- Also corrected `read-only` -> `read_only` in mapping files
Fixes issue #144
> Map `daily_energy_kwh` for all devices

- custom_components/connectlife/data_dictionaries/030-1wk100028v0w.yaml
- custom_components/connectlife/strings.json
- custom_components/connectlife/translations/en.json
Started mapping Hisense DH5S102BW tumble dryer
> 030-1wk100028v0w (Hisense DH5S102BW tumble dryer)

- custom_components/connectlife/data_dictionaries/008-304.yaml
This is a hisense Window air conditioner. tested and working within my HA environment
> Added support for device 008-304 (HiSense Window air conditioner)

- custom_components/connectlife/sensor.py
When calling the set value service, I get an unknown error. Looking at the logs I see this:
```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 816, in handle_execute_script
script_result = await script_obj.async_run(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
msg.get("variables"), context=context
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
return await asyncio.shield(create_eager_task(run.async_run()))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Fix calling set_value action

- custom_components/connectlife/data_dictionaries/015-000.yaml
- custom_components/connectlife/strings.json
- custom_components/connectlife/translations/en.json
I've tested these settings with my Asko dishwasher and they work fine. However, setting the child-lock only works if the dishwasher is turned on. I guess that is a limitation in the Connectlife platform as the app behaves the same.
* Expose 'remote control enabled' as a binary sensor.
* Expose 'child lock' as a switch
* Make 'door status' visible
* Use a more user friendly name for the 'remote control enabled' sensor
> fix(015-000): correct sensor types

- custom_components/connectlife/__init__.py
- custom_components/connectlife/services.py
- custom_components/connectlife/services.yaml
- custom_components/connectlife/strings.json
- custom_components/connectlife/translations/en.json
**Experimental** support for setting write only property `Actions`.
UI only supports known values for dishwashers, but the service will support any integer.
The service can be called for any ConnectLife _device_.
> Experimental set_action service

- custom_components/connectlife/data_dictionaries/015-000.yaml
- custom_components/connectlife/data_dictionaries/015-dishwasher-50.2f.yaml
- custom_components/connectlife/data_dictionaries/015-dishwasher-60.2.yaml
- custom_components/connectlife/strings.json
- custom_components/connectlife/translations/en.json
Support setting auto dose quantity (if already enabled), disable auto dose quantity, and enable/disable odor control.
Note that enabling auto dose seems to require quantity to be set to more than 0 in the same API request, which is currently not supporting.
Fixes #189
> More commands for dishwashers

- custom_components/connectlife/binary_sensor.py
- custom_components/connectlife/data_dictionaries/015-000.yaml
- custom_components/connectlife/data_dictionaries/README.md
- custom_components/connectlife/data_dictionaries/properties-schema.json
- custom_components/connectlife/dictionaries.py
- custom_components/connectlife/number.py
- custom_components/connectlife/select.py
- custom_components/connectlife/sensor.py
- custom_components/connectlife/switch.py
This adds support for entity_category. Now you can separate entities into a `diagnostics` and `config` category.
I implemented it in my fork since it allows me to separate all the `Error_f*` sensors into a diagnostics category for less clutter. 
I thought it might be interesting for others. 
I hope you don't mind the formatting changes that went along with it. It's VScodes auto-formatting for Python. If you have some auto-formatter that I could run, I wouldn't mind using your style. 
Example usage:
```yaml
- property: Error_f54
icon: mdi:dishwasher-alert
hide: true
entity_category: diagnostic
```
> Implement entity_category

- custom_components/connectlife/data_dictionaries/015-000.yaml
- custom_components/connectlife/data_dictionaries/015-dishwasher-50.2f.yaml
- custom_components/connectlife/data_dictionaries/015-dishwasher-60.2.yaml
- custom_components/connectlife/strings.json
- custom_components/connectlife/translations/en.json
* Make all alarms diagnostics sensors. They don't seem to work anyway. They always show ok.
* Fix switches for interior light at power off, super rinse aid, and tab setting. 
* Change Rinse_aid_refill and Auto_dose_refill to binary sensors of type problem. These show when you need to refill the rinse aid/dish wash, not the alarm.
* Fix order of stop/start in translations
> More sensor adjustments

- custom_components/connectlife/services.py
- custom_components/connectlife/services.yaml
- custom_components/connectlife/strings.json
- custom_components/connectlife/translations/en.json
This adds a generic update action that can target any device and will send the properties as a json. 
Properties are provided in yaml format to the action.
Allows users to experiment with the API easily and extend the functionality of the integration without waiting for updates.
Also fixed inconsistent spaces between strings.json and en.json translation file. Strings used 2, en used 4. Now they both use 2.
Example:
> generic update service

- custom_components/connectlife/data_dictionaries/008-301.yaml
The only issue I see is that the script generated an entry for daily_energy_kwh but the value is always reported as 0...
I based my work on another AC but also made sure to verify each entry to make sure it's working correctly
> Add mapping file for Hisense Window AC AW-08CWBRVGU01

- custom_components/connectlife/data_dictionaries/009-106.yaml
- custom_components/connectlife/data_dictionaries/009-109.yaml
- custom_components/connectlife/data_dictionaries/009-117.yaml
- custom_components/connectlife/data_dictionaries/009-129.yaml
- custom_components/connectlife/data_dictionaries/015-dishwasher-50.2f.yaml
- custom_components/connectlife/data_dictionaries/015-dishwasher-50.2t.yaml
- custom_components/connectlife/data_dictionaries/016-502.yaml
- custom_components/connectlife/data_dictionaries/025-1wj090660v0w.yaml
- custom_components/connectlife/data_dictionaries/025-1wj105246v0w.yaml
- custom_components/connectlife/data_dictionaries/026-1b0610z0049j.yaml
- custom_components/connectlife/data_dictionaries/026-1b0628z0075j.yaml
- custom_components/connectlife/data_dictionaries/026-1b0628z0146j.yaml
- custom_components/connectlife/data_dictionaries/027-washing-machine-wm22.yaml
- custom_components/connectlife/data_dictionaries/030-1wk080066v0w.yaml
- custom_components/connectlife/data_dictionaries/030-1wk100028v0w.yaml
- custom_components/connectlife/data_dictionaries/032-000.yaml
- custom_components/connectlife/data_dictionaries/properties-schema.json
- scripts/validate_mappings.py
- Updated mapping file schema to JSON Schema 2020-12
- Corrected default values for integers in schema
- Aligned schema with implementation:
- Allow empty sections for `binary_sensor`, `sensor`, and `switch`
- `binary_sensor` option value type is boolean
- `water_heater` option value type is boolean for target `is_away_mode_on`
- Added `scripts.validate_mappings` to check that all mapping files are valid
- Corrected invalid mapping files
> Validate mapping files

- custom_components/connectlife/data_dictionaries/015.yaml
The properties `Water_consumption_in_running_program` and `Energy_consumption_in_running_program` are marked as state_class = total. This is incorrect because the value resets to 0 on the commencements of a new dishwasher cycle. The correct state class for this is therefore `total_increasing`.
> Change energy and water consumption (running program) to `total_increasing` state class
